### ISSUE TITLE
“Error: charData should not contain characters not allowed in XML” thrown when generating Allure result file and error message contains ANSI sequence.

### ISSUE THREAD

**Issue by dtinth** [taskworld/prescript#27]
We at @taskworld noticed that when the Error message contains an ANSI escape sequence (color codes), the allure result file would not be generated. Instead, this error message is printed out to the console:

```
09:14:54  /var/lib/jenkins/workspace/E2E/node_modules/xmlcreate/lib/nodes/XmlCharData.js:75
09:14:54                  throw new Error("charData should not contain characters not allowed"
09:14:54                        ^
09:14:54  Error: charData should not contain characters not allowed in XML
09:14:54      at XmlCharData.set [as charData] (/var/lib/jenkins/workspace/E2E/node_modules/xmlcreate/lib/nodes/XmlCharData.js:75:23)
09:14:54      at new XmlCharData (/var/lib/jenkins/workspace/E2E/node_modules/xmlcreate/lib/nodes/XmlCharData.js:53:24)
09:14:54      at XmlElement.charData (/var/lib/jenkins/workspace/E2E/node_modules/xmlcreate/lib/nodes/XmlElement.js:168:28)
09:14:54      at parseString (/var/lib/jenkins/workspace/E2E/node_modules/js2xmlparser/lib/main.js:53:27)
09:14:54      at parseValue (/var/lib/jenkins/workspace/E2E/node_modules/js2xmlparser/lib/main.js:227:5)
09:14:54      at parseObjectOrMapEntry (/var/lib/jenkins/workspace/E2E/node_modules/js2xmlparser/lib/main.js:132:5)
09:14:54      at parseObjectOrMap (/var/lib/jenkins/workspace/E2E/node_modules/js2xmlparser/lib/main.js:152:13)
09:14:54      at parseValue (/var/lib/jenkins/workspace/E2E/node_modules/js2xmlparser/lib/main.js:220:9)
09:14:54      at parseObjectOrMapEntry (/var/lib/jenkins/workspace/E2E/node_modules/js2xmlparser/lib/main.js:132:5)
09:14:54      at parseObjectOrMap (/var/lib/jenkins/workspace/E2E/node_modules/js2xmlparser/lib/main.js:152:13)
```

**Comment by dtinth** [comment]
Fixed in latest release, v0.5555555.0
